services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      KAFKA_CLIENT_ID: PowerTrack_Retailer
      LOCAL_BROKER_IP: '127.0.0.1:9092'
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: timescale/timescaledb-ha:pg16
    restart: always
    ports:
      - 5432:5432
    environment:
      TIMESCALEDB_TELEMETRY: off
      POSTGRES_USER: postgres
      POSTGRES_DB: retailerEnergy
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
