services:
  debug-server:
    build:
      context: .
    environment:
      NODE_ENV: development
      DATABASE_URI: ${DATABASE_URI:-postgres://postgres:password@debug-db:5432/retailerEnergy}
      TEST_DATABASE_CLUSTER: ${TEST_DATABASE_CLUSTER:-postgres://postgres:password@debug-db:5432/}
      KAFKA_CLIENT_ID: ${KAFKA_CLIENT_ID:-PowerTrack_Retailer}
      LOCAL_BROKER_IP: ${LOCAL_BROKER_IP:-'127.0.0.1:9092'}
      DB_SETUP_FILE: ${DB_SETUP_FILE:-dbSetupInfo.json}
    ports:
      - 3000:3000
      - 9229:9229
    command: >
      sh -c "npm run database && npm run debug"
    depends_on:
      debug-db:
        condition: service_healthy
  debug-db:
    extends:
      file: compose.yaml
      service: db